### ISSUE TITLE
javascript.md - Błąd w formatowaniu Markdowna

### ISSUE THREAD

**Issue by jqdq** [ratajczykd/hci#2]
W ostatnim akapicie zamiast `##Przydatne linki:` powinno być `## Przydatne linki:`, bez spacji psuje się formatowanie w podglądzie GitHubowym i usuwa się domyślnie wstawiany tam enter.

Wcale nie stalkuję repozytorium HCI

**Comment by ratajczykd** [comment]
Dziękuję za zwrócenie uwagi :)

sob., 31 paź 2020 o 12:15 Jakub Dakowski <notifications@github.com>
napisał(a):
